language: python
env:
  global:
    - CC_TEST_REPORTER_ID=[6304c25454062b12a30c7471d682dc2a7e67a7e8830b625b278222a752d09db7]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .[all]
script:
  - pytest 
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
